name: push trigger
on: 
 push:
  branches:
    - main
    - develop
    - 'release/**'
 pull_request:
  types:
    - opened 
  branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "this is done by push trigger"
      
